[package]
name = "lumi"
version = "0.1.0"
authors = ["Martin <martin@martinb.dev>"]
readme = "README.md"
repository = "https://github.com/martin-bucinskas/lumi"
keywords = ["lumi", "os"]
edition = "2021"

[dependencies]
bootloader = "0.9.22"
